### ISSUE TITLE
Add installation instructions with homebrew on Mac

### ISSUE THREAD

**Issue by dpsanders** [itpplasma/GORILLA#2]
I think most people tend to use Homebrew, rather than macports, these days.

Part of [JOSS pre-review](https://github.com/openjournals/joss-reviews/issues/3116)

**Comment by micheder** [comment]
Unfortunately, there exists no Homebrew formula for the required Fortran library `netcdf-fortran`.
Thus, we have decided to use Macports instead, where this library exists.
